services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres
    user: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
        POSTGRES_PASSWORD: xyz
        POSTGRES_USER: alice
        POSTGRES_DB: currency_app
        PGPASSWORD: xyz
    command: ["postgres"]
    volumes:
      - currency-app-pg-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  currency-app-pg-data:

networks:
  backend:
